name: PR Checks

on:
  pull_request:
    branches: ['*']

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: |
          npm run lint
          npm run lint:mdx
          npm run format:check

      - name: Build
        run: npm run build 